### ISSUE TITLE
gcc missing when trying to use pyodbc in Python FaaS

### ISSUE THREAD

**Issue by DonSchenck** [boson-project/buildpacks#111]
I've added `pyodbc==4.0.31` to my requirements.txt file and it throws an error (missing gcc) when running `kn func build`. Both Windows 10 (Enterprise) and macOS. Here's the entire output from the command:

Error: executing lifecycle. This may be the result of using an untrusted builder: failed with status code: 145
output: 2021/07/29 16:17:12.168423 DEBUG:  Pulling image quay.io/boson/faas-python-builder:latest
latest: Pulling from boson/faas-python-builder
Digest: sha256:d4c39225cdf6d15e29e6f3e06efc5ceefed4be6faba9e8a2db8ed7c2b3293872
Status: Image is up to date for quay.io/boson/faas-python-builder:latest
2021/07/29 16:17:14.231505 DEBUG:  Selected run image quay.io/boson/faas-stack-run:python-v0.8.4
2021/07/29 16:17:15.465241 DEBUG:  Pulling image quay.io/boson/faas-stack-run:python-v0.8.4
python-v0.8.4: Pulling from boson/faas-stack-run
Digest: sha256:fd361d0fb342360662a9f8ae9047ee1af8cf1017ce886c05d8cca18f6188120a
Status: Image is up to date for quay.io/boson/faas-stack-run:python-v0.8.4
2021/07/29 16:17:16.521883 DEBUG:  Creating builder with the following buildpacks:
2021/07/29 16:17:16.521925 DEBUG:  -> dev.boson.python@0.0.1
2021/07/29 16:17:18.628562 DEBUG:  Pulling image buildpacksio/lifecycle:0.10.1
0.10.1: Pulling from buildpacksio/lifecycle
Digest: sha256:37bf981c31303cc022f9f37e079ecd571618a574177dcf2d2b0b19dcb4382c30
Status: Image is up to date for buildpacksio/lifecycle:0.10.1
2021/07/29 16:17:19.571897 DEBUG:  Using build cache volume pack-cache-donschenck_python-example_latest-fca58b728992.build
2021/07/29 16:17:19.571908 INFO:   ===> DETECTING
2021/07/29 16:17:19.572048 DEBUG:  Running the detector on OS linux with:
2021/07/29 16:17:19.572050 DEBUG:  Container Settings:
2021/07/29 16:17:19.572053 DEBUG:    Args: /cnb/lifecycle/detector
2021/07/29 16:17:19.572055 DEBUG:    System Envs: CNB_PLATFORM_API=0.4
2021/07/29 16:17:19.572058 DEBUG:    Image: pack.local/builder/626379726c6b73666f78:latest
2021/07/29 16:17:19.572060 DEBUG:    User: 
2021/07/29 16:17:19.572085 DEBUG:    Labels: map[author:pack]
2021/07/29 16:17:19.572086 DEBUG:  Host Settings:
2021/07/29 16:17:19.572089 DEBUG:    Binds: pack-layers-vglrjnaaif:/layers pack-app-fztjjlleoa:/workspace
2021/07/29 16:17:19.572091 DEBUG:    Network Mode: 
[detector] dev.boson.python 0.0.1
2021/07/29 16:17:21.429517 INFO:   ===> ANALYZING
2021/07/29 16:17:21.429697 DEBUG:  Running the analyzer on OS linux with:
2021/07/29 16:17:21.429713 DEBUG:  Container Settings:
2021/07/29 16:17:21.429719 DEBUG:    Args: /cnb/lifecycle/analyzer -daemon -cache-dir /cache docker.io/donschenck/python-example:latest
2021/07/29 16:17:21.429723 DEBUG:    System Envs: CNB_USER_ID=1000 CNB_GROUP_ID=1001 CNB_PLATFORM_API=0.4
2021/07/29 16:17:21.429726 DEBUG:    Image: buildpacksio/lifecycle:0.10.1
2021/07/29 16:17:21.429728 DEBUG:    User: root
2021/07/29 16:17:21.429740 DEBUG:    Labels: map[author:pack]
2021/07/29 16:17:21.429742 DEBUG:  Host Settings:
2021/07/29 16:17:21.429751 DEBUG:    Binds: /var/run/docker.sock:/var/run/docker.sock pack-cache-donschenck_python-example_latest-fca58b728992.build:/cache pack-layers-vglrjnaaif:/layers pack-app-fztjjlleoa:/workspace
2021/07/29 16:17:21.429761 DEBUG:    Network Mode: 
[analyzer] Previous image with name "docker.io/donschenck/python-example:latest" not found
2021/07/29 16:17:22.878390 INFO:   ===> RESTORING
2021/07/29 16:17:22.878491 DEBUG:  Running the restorer on OS linux with:
2021/07/29 16:17:22.878493 DEBUG:  Container Settings:
2021/07/29 16:17:22.878514 DEBUG:    Args: /cnb/lifecycle/restorer -cache-dir /cache
2021/07/29 16:17:22.878518 DEBUG:    System Envs: CNB_USER_ID=1000 CNB_GROUP_ID=1001 CNB_PLATFORM_API=0.4
2021/07/29 16:17:22.878521 DEBUG:    Image: buildpacksio/lifecycle:0.10.1
2021/07/29 16:17:22.878523 DEBUG:    User: root
2021/07/29 16:17:22.878534 DEBUG:    Labels: map[author:pack]
2021/07/29 16:17:22.878535 DEBUG:  Host Settings:
2021/07/29 16:17:22.878539 DEBUG:    Binds: pack-cache-donschenck_python-example_latest-fca58b728992.build:/cache pack-layers-vglrjnaaif:/layers pack-app-fztjjlleoa:/workspace
2021/07/29 16:17:22.878541 DEBUG:    Network Mode: 
2021/07/29 16:17:24.158922 INFO:   ===> BUILDING
2021/07/29 16:17:24.159036 DEBUG:  Running the builder on OS linux with:
2021/07/29 16:17:24.159038 DEBUG:  Container Settings:
2021/07/29 16:17:24.159042 DEBUG:    Args: /cnb/lifecycle/builder
2021/07/29 16:17:24.159044 DEBUG:    System Envs: CNB_PLATFORM_API=0.4
2021/07/29 16:17:24.159056 DEBUG:    Image: pack.local/builder/626379726c6b73666f78:latest
2021/07/29 16:17:24.159080 DEBUG:    User: 
2021/07/29 16:17:24.159091 DEBUG:    Labels: map[author:pack]
2021/07/29 16:17:24.159092 DEBUG:  Host Settings:
2021/07/29 16:17:24.159095 DEBUG:    Binds: pack-layers-vglrjnaaif:/layers pack-app-fztjjlleoa:/workspace
2021/07/29 16:17:24.159097 DEBUG:    Network Mode: 
[builder] ---> Python Function Buildpack
[builder] ---> Installing function
[builder] total 16
[builder] -rw-r--r-- 1 cnb cnb 265 Jul 29 17:14 func.py
[builder] -rw-r--r-- 1 cnb cnb 255 Jul 29 20:17 func.yaml
[builder] -rw-r--r-- 1 cnb cnb  42 Jul 29 17:14 requirements.txt
[builder] -rw-r--r-- 1 cnb cnb 259 Jul 29 17:13 test_func.py
[builder] ---> Installing or reusing runtime dependencies
[builder] Using python version Python 3.8.6
[builder] Installing invoker dependencies
[builder] Installing virtualenv
[builder] Collecting virtualenv
[builder]   Downloading https://files.pythonhosted.org/packages/bc/c1/03d8fe7a20b4b2546037c36e5e0f6080522d36421fbbf4d91211fadac150/virtualenv-20.6.0-py2.py3-none-any.whl (5.3MB)
[builder] Collecting distlib<1,>=0.3.1
[builder]   Downloading https://files.pythonhosted.org/packages/87/26/f6a23dd3e578132cf924e0dd5d4e055af0cd4ab43e2a9f10b7568bfb39d9/distlib-0.3.2-py2.py3-none-any.whl (338kB)
[builder] Collecting filelock<4,>=3.0.0
[builder]   Downloading https://files.pythonhosted.org/packages/93/83/71a2ee6158bb9f39a90c0dea1637f81d5eef866e188e1971a1b1ab01a35a/filelock-3.0.12-py3-none-any.whl
[builder] Collecting platformdirs<3,>=2
[builder]   Downloading https://files.pythonhosted.org/packages/a5/a6/45f6d6b848d7ac273f261b35ed048ea8f301d2ec0594fbcf7616b4012f45/platformdirs-2.2.0-py3-none-any.whl
[builder] Collecting six<2,>=1.9.0
[builder]   Downloading https://files.pythonhosted.org/packages/d9/5a/e7c31adbe875f2abbb91bd84cf2dc52d792b5a01506781dbcf25c91daf11/six-1.16.0-py2.py3-none-any.whl
[builder] Collecting backports.entry-points-selectable>=1.0.4
[builder]   Downloading https://files.pythonhosted.org/packages/0c/cd/1e156227cad9f599524eb10af62a2362f872910a49402dbd2bea2dedc91c/backports.entry_points_selectable-1.1.0-py2.py3-none-any.whl
[builder] Installing collected packages: distlib, filelock, platformdirs, six, backports.entry-points-selectable, virtualenv
[builder]   WARNING: The script virtualenv is installed in '/workspace/.local/bin' which is not on PATH.
[builder]   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
[builder] Successfully installed backports.entry-points-selectable-1.1.0 distlib-0.3.2 filelock-3.0.12 platformdirs-2.2.0 six-1.16.0 virtualenv-20.6.0
[builder] Creating functions runtime environment
[builder] Activating functions environment
[builder] Installing parliament
[builder] Collecting parliament-functions
[builder]   Downloading https://files.pythonhosted.org/packages/3c/d0/eaa4ac3c9cdc873b8f468454df4aa2426bd29844d6fe2c7434880354f20e/parliament_functions-0.1.0-py3-none-any.whl
[builder] Collecting flask
[builder]   Downloading https://files.pythonhosted.org/packages/54/4f/1b294c1a4ab7b2ad5ca5fc4a9a65a22ef1ac48be126289d97668852d4ab3/Flask-2.0.1-py3-none-any.whl (94kB)
[builder] Collecting waitress
[builder]   Downloading https://files.pythonhosted.org/packages/a8/cf/a9e9590023684dbf4e7861e261b0cfd6498a62396c748e661577ca720a29/waitress-2.0.0-py3-none-any.whl (56kB)
[builder] Collecting cloudevents
[builder]   Downloading https://files.pythonhosted.org/packages/c7/68/4d24e94a2afd437587dbed9863446a2294ac85084819f76185fa31767fdc/cloudevents-1.2.0-py3-none-any.whl
[builder] Collecting Jinja2>=3.0
[builder]   Downloading https://files.pythonhosted.org/packages/80/21/ae597efc7ed8caaa43fb35062288baaf99a7d43ff0cf66452ddf47604ee6/Jinja2-3.0.1-py3-none-any.whl (133kB)
[builder] Collecting Werkzeug>=2.0
[builder]   Downloading https://files.pythonhosted.org/packages/bd/24/11c3ea5a7e866bf2d97f0501d0b4b1c9bbeade102bb4b588f0d2919a5212/Werkzeug-2.0.1-py3-none-any.whl (288kB)
[builder] Collecting itsdangerous>=2.0
[builder]   Downloading https://files.pythonhosted.org/packages/9c/96/26f935afba9cd6140216da5add223a0c465b99d0f112b68a4ca426441019/itsdangerous-2.0.1-py3-none-any.whl
[builder] Collecting click>=7.1.2
[builder]   Downloading https://files.pythonhosted.org/packages/76/0a/b6c5f311e32aeb3b406e03c079ade51e905ea630fc19d1262a46249c1c86/click-8.0.1-py3-none-any.whl (97kB)
[builder] Collecting deprecation<3.0,>=2.0
[builder]   Downloading https://files.pythonhosted.org/packages/02/c3/253a89ee03fc9b9682f1541728eb66db7db22148cd94f89ab22528cd1e1b/deprecation-2.1.0-py2.py3-none-any.whl
[builder] Collecting MarkupSafe>=2.0
[builder]   Downloading https://files.pythonhosted.org/packages/68/ba/7a5ca0f9b4239e6fd846dd54c0b5928187355fa62fbdbd13e1c5942afae7/MarkupSafe-2.0.1-cp38-cp38-manylinux2010_x86_64.whl
[builder] Collecting packaging
[builder]   Downloading https://files.pythonhosted.org/packages/3c/77/e2362b676dc5008d81be423070dd9577fa03be5da2ba1105811900fda546/packaging-21.0-py3-none-any.whl (40kB)
[builder] Collecting pyparsing>=2.0.2
[builder]   Downloading https://files.pythonhosted.org/packages/8a/bb/488841f56197b13700afd5658fc279a2025a39e22449b7cf29864669b15d/pyparsing-2.4.7-py2.py3-none-any.whl (67kB)
[builder] Installing collected packages: MarkupSafe, Jinja2, Werkzeug, itsdangerous, click, flask, waitress, pyparsing, packaging, deprecation, cloudevents, parliament-functions
[builder] Successfully installed Jinja2-3.0.1 MarkupSafe-2.0.1 Werkzeug-2.0.1 click-8.0.1 cloudevents-1.2.0 deprecation-2.1.0 flask-2.0.1 itsdangerous-2.0.1 packaging-21.0 parliament-functions-0.1.0 pyparsing-2.4.7 waitress-2.0.0
[builder] WARNING: You are using pip version 19.3.1; however, version 21.2.1 is available.
[builder] You should consider upgrading via the 'pip install --upgrade pip' command.
[builder] Installing user dependencies
[builder] Requirement already satisfied: parliament-functions==0.1.0 in ./functions/lib/python3.8/site-packages (from -r /layers/dev.boson.python/app/requirements.txt (line 1)) (0.1.0)
[builder] Collecting pyodbc==4.0.31
[builder]   Downloading https://files.pythonhosted.org/packages/f2/20/fce702980820fedf856c95787c20a5bbe2bbe4e141d56c7a5004fe6b06fa/pyodbc-4.0.31.tar.gz (280kB)
[builder] Requirement already satisfied: flask in ./functions/lib/python3.8/site-packages (from parliament-functions==0.1.0->-r /layers/dev.boson.python/app/requirements.txt (line 1)) (2.0.1)
[builder] Requirement already satisfied: waitress in ./functions/lib/python3.8/site-packages (from parliament-functions==0.1.0->-r /layers/dev.boson.python/app/requirements.txt (line 1)) (2.0.0)
[builder] Requirement already satisfied: cloudevents in ./functions/lib/python3.8/site-packages (from parliament-functions==0.1.0->-r /layers/dev.boson.python/app/requirements.txt (line 1)) (1.2.0)
[builder] Requirement already satisfied: Jinja2>=3.0 in ./functions/lib/python3.8/site-packages (from flask->parliament-functions==0.1.0->-r /layers/dev.boson.python/app/requirements.txt (line 1)) (3.0.1)
[builder] Requirement already satisfied: itsdangerous>=2.0 in ./functions/lib/python3.8/site-packages (from flask->parliament-functions==0.1.0->-r /layers/dev.boson.python/app/requirements.txt (line 1)) (2.0.1)
[builder] Requirement already satisfied: click>=7.1.2 in ./functions/lib/python3.8/site-packages (from flask->parliament-functions==0.1.0->-r /layers/dev.boson.python/app/requirements.txt (line 1)) (8.0.1)
[builder] Requirement already satisfied: Werkzeug>=2.0 in ./functions/lib/python3.8/site-packages (from flask->parliament-functions==0.1.0->-r /layers/dev.boson.python/app/requirements.txt (line 1)) (2.0.1)
[builder] Requirement already satisfied: deprecation<3.0,>=2.0 in ./functions/lib/python3.8/site-packages (from cloudevents->parliament-functions==0.1.0->-r /layers/dev.boson.python/app/requirements.txt (line 1)) (2.1.0)
[builder] Requirement already satisfied: MarkupSafe>=2.0 in ./functions/lib/python3.8/site-packages (from Jinja2>=3.0->flask->parliament-functions==0.1.0->-r /layers/dev.boson.python/app/requirements.txt (line 1)) (2.0.1)
[builder] Requirement already satisfied: packaging in ./functions/lib/python3.8/site-packages (from deprecation<3.0,>=2.0->cloudevents->parliament-functions==0.1.0->-r /layers/dev.boson.python/app/requirements.txt (line 1)) (21.0)
[builder] Requirement already satisfied: pyparsing>=2.0.2 in ./functions/lib/python3.8/site-packages (from packaging->deprecation<3.0,>=2.0->cloudevents->parliament-functions==0.1.0->-r /layers/dev.boson.python/app/requirements.txt (line 1)) (2.4.7)
[builder] Installing collected packages: pyodbc
[builder]     Running setup.py install for pyodbc: started
[builder]     Running setup.py install for pyodbc: finished with status 'error'
[builder]     ERROR: Command errored out with exit status 1:
[builder]      command: /layers/dev.boson.python/environments/functions/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-74r_l5zb/pyodbc/setup.py'"'"'; __file__='"'"'/tmp/pip-install-74r_l5zb/pyodbc/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-tszr4sy7/install-record.txt --single-version-externally-managed --compile --install-headers /layers/dev.boson.python/environments/functions/include/site/python3.8/pyodbc
[builder]          cwd: /tmp/pip-install-74r_l5zb/pyodbc/
[builder]     Complete output (10 lines):
[builder]     running install
[builder]     running build
[builder]     running build_ext
[builder]     building 'pyodbc' extension
[builder]     creating build
[builder]     creating build/temp.linux-x86_64-3.8
[builder]     creating build/temp.linux-x86_64-3.8/src
[builder]     gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DPYODBC_VERSION=4.0.31 -I/layers/dev.boson.python/environments/functions/include -I/usr/include/python3.8 -c src/buffer.cpp -o build/temp.linux-x86_64-3.8/src/buffer.o -Wno-write-strings
[builder]     unable to execute 'gcc': No such file or directory
[builder]     error: command 'gcc' failed with exit status 1
[builder]     ----------------------------------------
[builder] ERROR: Command errored out with exit status 1: /layers/dev.boson.python/environments/functions/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-74r_l5zb/pyodbc/setup.py'"'"'; __file__='"'"'/tmp/pip-install-74r_l5zb/pyodbc/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-tszr4sy7/install-record.txt --single-version-externally-managed --compile --install-headers /layers/dev.boson.python/environments/functions/include/site/python3.8/pyodbc Check the logs for full command output.
[builder] WARNING: You are using pip version 19.3.1; however, version 21.2.1 is available.
[builder] You should consider upgrading via the 'pip install --upgrade pip' command.
[builder] ERROR: failed to build: exit status 1

**Comment by zroubalik** [comment]
gcc is missing in the base image.
