### ISSUE TITLE
Enable JVM mode for Quarkus

### ISSUE THREAD

**Issue by matejvasek** [boson-project/buildpacks#29]
Currently only native build is supported. Build of native binary takes longer time than *.jar,, for developer it may be useful use JVM mode for quick iteration.

**Comment by lance** [comment]
@matejvasek would this be a completely separate buildpack? How will the `faas` CLI know which to use?

**Comment by matejvasek** [comment]
@lance Unfortunately yes,  most likely it would be separate buildpack. I would prefer to have just single buildpack and control build process by environment variable, with that I could choose resulting artifact -- native binary or jar, but I can't change run-image that way.

So with just single buildpack I could easily build both native and jar, but they would share runner image, meaning I would include JVM even for native. UBI minimal is cca 100MB without JVM and cca 300MB with JVM.

For `faas` CLI this needs to be discussed. Maybe we could add new flag `--mode` which could have values like `JVM`, `native`, `debug`, `release`.

**Comment by zroubalik** [comment]
> For `faas` CLI this needs to be discussed. Maybe we could add new flag `--mode` which could have values like `JVM`, `native`, `debug`, `release`.

We should support update/migration of the existing function from `JVM` to `native` and vice versa. I can imagine an usecase where users is using `JVM` mode for function development and once he is done, he would like to easily convert to the `native` one (eg. with `faas update`).

**Comment by matejvasek** [comment]
Yes, user definitely will change modes. So the flag should be available for `build`,`update` and `create` sub-commands.

**Comment by zroubalik** [comment]
@matejvasek just a nit. `init` sub-command as well 😄

**Comment by matejvasek** [comment]
@zroubalik  Maybe, what would it do, put default mode value into config file?

**Comment by zroubalik** [comment]
@matejvasek correct me if I am wrong (most probably I am), I thought there are different maven deps/profiles for both modes.

**Comment by matejvasek** [comment]
@zroubalik pom.xml is same, native build is activated by profile on cmd line, so `mvn package` for jvm build and `mvn package -Pnative` for native build.

**Comment by lance** [comment]
OK, so for Quarkus there would be `jvm` and `native`. For Node.js `debug` and `production`. What about Golang?

**Comment by lance** [comment]
@matejvasek should this be closed now that https://github.com/boson-project/buildpacks/pull/30 and https://github.com/boson-project/faas/pull/147 have landed?
