### ISSUE TITLE
change stack id prefix

### ISSUE THREAD

**Issue by lance** [boson-project/buildpacks#42]
Currently, each of the stacks has a stack ID prefix of `com.redhat.faas.stacks`. It's defined here.

https://github.com/boson-project/buildpacks/blob/bb77a3dfb1c1d1bfea66224503e60ea1538d58ee/stacks/build-stack.sh#L4

The stack IDs should probably not be constrained to `faas` at all, since there is nothing specific to functions in these stacks. I suggest changing the stack ID prefix to `com.redhat.stacks`.

The change will ripple down into the `builder.toml` and `buildpack.toml` files for the builders and buildpacks respectively.

/cc @boson-project/core

**Comment by zroubalik** [comment]
I wonder whether we should use `com.redhat...`, if I am not mistaken, this is not an official RH produced stack? Shouldn't we use something like `dev.boson...` ?

**Comment by lance** [comment]
> Shouldn't we use something like `dev.boson`...

Yes you are probably right! Too late for DP though. :rofl:
