### ISSUE TITLE
Figure out image tags/versions

### ISSUE THREAD

**Issue by lance** [boson-project/buildpacks#5]
Currently we are modeling our images based on the official [buildpack samples](https://github.com/buildpacks/samples). However tagging and versioning are a little confusing in this model.

For example, all of the "stack" images are named `faas-stack-*` where `*` is `base|build|run` and the tags are the language. For example, to use the Node.js run image, you would use `quay.io/boson/faas-stack-run:nodejs`. This is clean looking but implies a floating tag. Should we also be tagging specific version numbers? E.g. `quay.io/boson/faas-stack-run:nodejs-1.0.0`.

The actual buildpack images are slightly different than the stack images. For the buildpack images, we are creating for example `quay.io/boson/faas-nodejs-bp`. The image itself distinguishes it as a Node.js buildpack. Currently there is nothing but a `latest` tag on the buildpack images. We should determine how we want to version these.

**Comment by lkingland** [comment]
Adding an additional tag with the version suffix is a good option, because we then let the user decide which suits their situation better.

**Comment by lance** [comment]
Closing as this has been addressed in multiple PRs and automated CI/publication of images.
